### ISSUE TITLE
[InvalidArgumentException] 

### ISSUE THREAD

**Issue by baig772** [diadal/passport#3]
When I run 

> composer require diadal/passport

 I see the following

>  [InvalidArgumentException]                                                                                                                   
>   Could not find a version of package diadal/passport matching your minimum-stability (stable). Require it with an explicit version constrain  
>   t allowing its desired stability.

**Comment by diadal** [comment]
it work great with laravel 5.7  try create new project and see if the error will come up

**Comment by diadal** [comment]
what is your php version below are the requirements
```
requires

webpatser/laravel-uuid: ^3.0
php: >=7.1
laravel/passport: 6.*|7.*

```

**Comment by baig772** [comment]
Tried, same issue. PHP versio in 7.2

**Comment by diadal** [comment]
on a new project it installed without error 
it work I try to find error no error 
<img width="1027" alt="screen shot 2018-11-20 at 8 29 45 pm" src="https://user-images.githubusercontent.com/19895516/48797697-31bdb080-ed03-11e8-8e76-56daba5ed842.png">
